core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('',views.index,name='index'),
    path('services',views.services,name='services'),
    path('astuces',views.astuces,name='astuces'),
    path('a propos',views.a_propos,name = 'a_propos')
    
]

gbs_site/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("core.urls",namespace='core'))
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL,
document_root = settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render


def index(request):
    return render(request,"core/index.html")

def services(request):
    return render(request,"core/services.html")

def a_propos(request):
    return render(request,"core/a_propos.html")

def astuces(request):
    return render(request,"core/astuces.html")
def a_propos(request):
    return render(request,"core/a_propos.html")

core/templates/core/a_propos.html
{% extends "core/base.html" %}
{% load static %}

{% block header %}
<span><br></span>
<span><br></span>

{% endblock header %}
{% block content %}
<div  style="justify-content: center;">
    <style>
        body{
            background-color: darkslategrey;
        }
        .image-holder{
            display: flex; 
            justify-content: right;
            margin-top: 30px;
            width: 400px;
            height: 350px;
        }
        #back-img{
            border-radius: 150px;
            width:100%;
            height: 80%;

        }
        .text-container{
            position: relative;
            bottom: 140px;
            left: 50px;
            margin-top: 20px;
            padding: 20px;
            margin-top: 0;            
            background: rosybrown;
            border-radius: 10px;
        }
        p{
            padding-top: 0;
            display: flex;
            text-align:left;
            justify-content: center;
            border-radius: 10px;
            width: 70%;
        }
        .text-container h3{
            margin-top: 20px;
        }
        .whatsapp-btn{
            display: inline-block;
            width: 90%;
            background-color: green;
            cursor: pointer;
            border-radius: 20px;
        }
    </style>
     
    <div class="image-holder">
        <img id="back-img" src="{% static 'gbs_images/ou-trouver-un-institut-de-beaute-en-martinique-body-touch.jpg' %}" alt="institute-image">
    </div>
   
    <div class="text-container">
        <h3><strong>Qui Sommes-nous ?</strong> </h3>
    <p>Chez Glamourbeauty&spa, nous sommes là pour vous aider à prendre soin de vous, 
    de la tête aux pieds.<br><br>
    Nous proposons une large gamme de soins 
    allant des traitements du visage aux massages en passant par les soins des ongles.<br><br>
    Nous avons tout ce qu'il vous faut pour vous sentir belle et détendue. 
    Venez découvrir notre institut de beauté et profitez de nos soins de qualité.
        </p>
        <a href="https://wa.me/+237656593891">
<button class="whatsapp-btn">
    
        contactez nous sur whatsapp &nbsp; <i class="fa fa-whatsapp"></i>
        </button></a>
    </div>
    
</div>
{% endblock content %}

core/templates/core/astuces.html
{% extends "core/base.html" %}
{% load static %}

{% block header %}
<p></p>
<h2 style="color: aquamarine; margin-left: 9vh;">des Astuces beauté pour vous aider a vous sublimer au quotidien</h2>
{% endblock header %}

{% block content %}
<hr style="margin:2rem ;">

<div class="container my-5">
    <style>
        .astuces{
            border-radius: 25px;

        }
    </style>
    <div class="p-5 text-center bg-body-tertiary rounded-3">
        <img class="astuces" src="{% static 'gbs_images/1698613825391.jpg' %}" width="100%" height="100%">
        <svg class="bi mt-4 mb-3" style="color: var(--bs-indigo);" width="100" height="100"><use xlink:href="#bootstrap"/></svg>
      
    </div>
  </div>

  <hr style="margin:2rem ;">

  <div class="container my-5">
    <div class="p-5 text-center bg-body-tertiary rounded-3">
        <img class="astuces" src="{% static 'gbs_images/1698081988885.jpg' %}" width="100%" height="100%">
        <svg class="bi mt-4 mb-3" style="color: var(--bs-indigo);" width="100" height="100"><use xlink:href="#bootstrap"/></svg>
      
    </div>
  </div>

  <hr style="margin:2rem ;">

  <div class="container my-5">
    <div class="p-5 text-center bg-body-tertiary rounded-3">
        <img class="astuces" src="{% static 'gbs_images/1698613839290.jpg' %}" width="100%" height="100%">
        <svg class="bi mt-4 mb-3" style="color: var(--bs-indigo);" width="100" height="100"><use xlink:href="#bootstrap"/></svg>
      
    </div>
  </div>

  <hr style="margin:2rem ;">
  

  <div class="container my-5">
    <div class="p-5 text-center bg-body-tertiary rounded-3">
        <img class="astuces" src="{% static 'gbs_images/1698613852600.jpg' %}" width="100%" height="100%">
        <svg class="bi mt-4 mb-3" style="color: var(--bs-indigo);" width="100" height="100"><use xlink:href="#bootstrap"/></svg>
      
    </div>
  </div>

  </div>
{% endblock content %}

core/templates/core/base.html
{% load bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">
<head>
  
    <title>Glamour Beauty & Spa</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.118.2">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/carousel/">

    

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

   {% bootstrap_css %}
   {% bootstrap_javascript %}

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins');
        *{
            
            font-family: 'Poppins','Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        }
        .xbet{
        margin: 50px;
        }
       
      .xbet a{
        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        display: flex;
        justify-content: right;
        text-decoration:none;

        color: black;
      }
      .xbet span{
        display: inline-block;
        position: relative;
        top: 75px;
        right: 120px;
      color: blue;
      font-weight: 50;

      }
        .item img{ 
          border-radius: 30px; 
          width: 20%; 
          height: 20%; 
          padding: 10px;
        }
        .round-header{
          border-radius: 50px;
        }

        /*
        body{
            
            background-image:url("{% static 'backimgs2.jpg' %}");
            
            color: beige;
            /* display: flex;
            align-items: center;
            background-position: center;
        }*/
        .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
      i{
        width: 30px;
      }

       

    </style>
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
    <link href="{% static 'css/jumbotrons.css' %}" rel="stylesheet">

</head>
<body>
    <header data-bs-theme="blue">
    
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <!--
        <div class="container-fluid">
            <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    -->
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'core:index' %}">Glamour Beauty & Spa</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
           
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:services' %}">Nos services</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:a_propos' %}">A propos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:astuces' %}">Astuces Beaute</a>
            </li>
            
              
              
              
          </ul>
          
        </div>
      </div>
        
        
    </nav>
</header>

  
    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>

    </div>
    <div class="container">
      <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
            <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
          </a>
          <span class="mb-3 mb-md-0 text-body-secondary">&copy; Glamour Beauty & Spa</span>
        </div>
    
        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
          <br><li class="ms-3"><a class="text-body-secondary" href="https://www.facebook.com/lievrepat"><i class="fa fa-facebook" ></i></a></li>
          <br><li class="ms-3"><a class="text-body-secondary" href="https://wa.me/+237656593891"><i class="fa fa-whatsapp" ></i></a>&nbsp;</li><br>
          <br><li class="ms-3"><i class="fa fa-map-marker" ></i>&nbsp;Yaounde, Essos Face elise bar </li>
        </ul>
        <a href="#"><i class="fa fa-arrow-up"></i>&nbsp;Remonter</a>
      </footer>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</body>


</html>

core/templates/core/index.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
<main>
  

  <div id="myCarousel" class="carousel slide mb-6" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="3" aria-label="Slide 4"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        
        <img src="{% static 'gbs_images/0-0000000hammam.jpg' %}" width="100%" height="100%">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect  width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>
        
        <div class="container" style="width: 120px;">
          
          <div class="carousel-caption text-start">
            <h1>Hammam</h1>
            <p class="opacity-75">redonnez vie a votre peau dans nos salles </p>
            
            <!--<p><a class="btn btn-lg btn-primary" href="">Connectez vous</a></p>-->
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'gbs_images/cc0dbd380c457854450f7f6f9a0cf780.jpg' %}" width="100%" height="100%">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>
        <div class="container">
          <div class="carousel-caption">
            <h1>Coiffure Homme</h1>
            <p>La coiffure c'est la base de la beauté</p>
            
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'gbs_images/61n9pdG+QkL._AC_UF894,1000_QL80_.jpg' %}" width="100%" height="100%">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>
        <div class="container">
          <div class="carousel-caption text-end">
            <h1>Perruques</h1>
            <p>Les plus belles perruques sont chez glamour beauty & spa</p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'gbs_images/onglerie-intemporelle-saint-christol-les-ales-1.jpg' %}" width="100%" height="100%">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>
        <div class="container">
          <div class="carousel-caption text-end">
            <h1>Onglerie</h1>
            <p>Posez vos ongles a des prix incroyables</p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

<div class="xbet">
  
  <a href="https://refpa4948989.top/L?tag=d_2856455m_1573c_&site=2856455&ad=1573"> obtenez 300% de bonus avec le code promo <br><span>1x_1355302&nbsp;&nbsp;&nbsp;<i class="fa fa-download"></i></span>
  <img width="50%" height="35%" src="{% static 'gbs_images/1xbet-780x440.jpg' %}" alt="1xBET promo">
</a>
 

</div>
  <div class="container marketing">
  

      <div class="row">
        <div class="col-lg-4">
            </p>
            <a href="">
                <img class="round-header" src="{% static 'gbs_images/611ulWGAV2L._AC_UF1000,1000_QL80_.jpg' %}" width="100px" height="100px">
              </a>
              <h2 class="fw-normal">des perruques de qualité</h2>
          <p>perruques simple,avec lace frontale, longs,fin,court il y en a pour tous </p>
          <p><a class="btn btn-secondary" href="{% url 'core:services' %}">Voir plus &raquo;</a></p>
               
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <a href="">
                <img class="round-header" src="{% static 'gbs_images/1698565492018.jpg' %}" width="100px" height="100px">
              </a>
          <h2 class="fw-normal">Soins de visage complet avec Luminotherapie</h2>
          <p>ravivez votre jeunesse et revelez tout le potentiel de votre beauté avec la luminotherapie<p>
            <a class="btn btn-secondary" href="{% url 'core:services' %}">Voir plus &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        
        <div class="col-lg-4">
            <a href="">
                <img class="round-header" src="{% static 'gbs_images/1698565579904.jpg' %}" width="100px" height="100px">
              </a>
          <h2 class="fw-normal">Des produits de qualité</h2>
          <p>A gbs, on prend soins de vos cheveux en utilisant des produits qui ont deja fait leurs preuves</p>
          <p><a class="btn btn-secondary" href="{% url 'core:services' %}">Voir plus &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->
      <p class="whatsapp-btn">
        Contactez nous sur whatsapp &nbsp; <a href="https://wa.me/+237656593891"><button  class="btn btn-outline-success" type="submit"><i class="fa fa-whatsapp"></i></button>
      </a>
        </p>


  </div><!-- /.container -->
</main>


{% endblock content %}

core/templates/core/services.html
{% extends "core/base.html" %}
{% load static %}

{% block header %}

{% endblock header %}

{% block content %}

<!-- START THE FEATURETTES -->
<div class="container marketing">
    <style>
        h2{
            color:blueviolet;
        }
        .prix-coiffure span{
            color: mediumpurple;
        }
        .whatsapp-btn{
          padding-bottom: 4em;
        }
        
    </style>

    <hr class="featurette-divider">
    <p class="whatsapp-btn">
      Contactez nous sur whatsapp &nbsp; <a href="https://wa.me/+237656593891"><button  class="btn btn-outline-success" type="submit"><i class="fa fa-whatsapp"></i></button>
    </a>
      </p>

<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading fw-normal lh-1">Soins Corporels/Soins de visage. <span class="text-body-secondary">Vous n'en reviendrais pas!</span></h2>
    <p class="lead">regagner une peau parfaite  a des prix defiants toute concurrences</p>
  </div>
  <div class="col-md-5">
    
    <img  src="{% static 'gbs_images/1698565519237.jpg' %}" width="90%" height="80%">  </div>
<hr class="featurette-divider">
</div>



<div class="row featurette">
  <div class="col-md-7 order-md-2">
    <h2 class="featurette-heading fw-normal lh-1">Hamman, Gommage, Massage. <span class="text-body-secondary">resultats  visibles dès la première séance </span></h2>
    <p class="lead">Faites vous donc unpeu bichoner par nos experts !!</p>
  </div>
  <div class="col-md-5 order-md-1">
    
    <img src="{% static 'gbs_images/B9731973899Z.1_20220905112441_000+G13L627QJ.1-0.jpg' %}" width="100%" height="100%">  </div>
    </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading fw-normal lh-1">Manicure,Pedicure,Onglerie, <span class="text-body-secondary">tellement beau</span></h2>
    <p class="lead">Pose capsule & vernis gel,gainage,construction et resine</p>
  </div>
  <div class="col-md-5">
    <img src="{% static 'gbs_images/Nail-Art-Baby-Boomer.jpg' %}" width="100%" height="100%">
    </div>
</div>

<hr class="featurette-divider">
<div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading fw-normal lh-1">Coiffure Homme & Enfants. <span class="text-body-secondary"></span></h2>
      <p class="lead">
      </p>
    </div>
    <div class="col-md-5">
      <img src="{% static 'gbs_images/dca51a068f12bed4b8661301ff937279.jpg' %}" width="100%" height="100%">
      </div>
</div>
      <hr class="featurette-divider">
      

      <div class="row featurette">
        <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading fw-normal lh-1">Coiffure Femme. <span class="text-body-secondary"></span></h2>
            <p class="lead">
            </p>
        </div>
        <div class="col-md-5 order-md-1">
          
          <img src="{% static 'gbs_images/1698613549190.jpg' %}" width="100%" height="100%">  </div>
          </div>
      </div>

      <hr class="featurette-divider">
      
      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading fw-normal lh-1">Formation  <span class="text-body-secondary"></span></h2>
          <p class="lead">Pour les passionés qui veulent pouvoir en faire autant</p>
        </div>
        <div class="col-md-5">
          <!--
          <svg  width="100" height="100">
            <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
          </svg>
        -->
          <img src="{% static 'gbs_images/LOREAL_0088302_ORI_0.jpg' %}" width="100%" height="100%">
          </div>
      </div>

<hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading fw-normal lh-1">Traitement de cheveux. <span class="text-body-secondary"></span></h2>
            <p class="lead">
             <ul>
            <li class="prix-coiffure"><span>Vente de meches et perruques:&nbsp;</span><i class="fa fa-check"></i></li>
            <li class="prix-coiffure"><span>Vente de produits d'entredtien:&nbsp;</span><i class="fa fa-check"></i></li>
            <li class="prix-coiffure"><span>coloration:&nbsp;</span><i class="fa fa-check"></i></li>
        </ul>

            </p>
        </div>
        <div class="col-md-5 order-md-1">
          
          <img src="{% static 'gbs_images/perruque femme cancer.jpg' %}" width="100%" height="100%">  </div>
          </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading fw-normal lh-1">Vente de produit d'entretien<span class="text-body-secondary"></span></h2>
          <p class="lead">Pour vos besoins personels</p>
        </div>
        <div class="col-md-5">
          <img src="{% static 'gbs_images/1698565582861.jpg' %}" width="90%" height="100%">
          </div>
      </div>

<hr class="featurette-divider">

<!-- /END THE FEATURETTES -->
</div><!-- /.container -->


{% endblock content %}